#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f spiderlab.key; then
  echo "Error: spiderlab.key already exists"
  exit 1
fi

if test -f spiderlab.crt; then
  echo "Error: spiderlab.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out spiderlab.crt -keyout spiderlab.key -subj "/CN=localhost"

chmod 600 spiderlab.crt
chmod 600 spiderlab.key